### ISSUE TITLE
AssetManager singleton? (or some global reference)

### ISSUE THREAD

**Issue by JacopoG** [DeimosA/PlayingWithMagic#36]
Does it make sense to create a singleton for the assetManager or should we pass it to each system that needs it? I'm guessing it is to be used every time we need to get a texture, so I think it will be needed in a lot of places. What do you think?

EDIT: I hadn't seen the pull request #33, so maybe this issue isn't relevant any more. I have to check the new code more carefully to understand how to use it.

**Comment by DeimosA** [comment]
No, but KTX has a simple dependency injection that would help with this

**Comment by JacopoG** [comment]
@DeimosA nice to know, thank you. You mean [this one](https://github.com/libktx/ktx/tree/master/inject), right? Did you already used somewhere in the code so I can take a look?
