### ISSUE TITLE
On-screen buttons

### ISSUE THREAD

**Issue by DeimosA** [DeimosA/PlayingWithMagic#48]
in ButtonsWidget
- [ ] Bomb button with cooldown

**Comment by JacopoG** [comment]
I think the cooldown is easier and suitable for the gameplay. I don't think we need other buttons right now.

**Comment by DeimosA** [comment]
i guess cooldown should be implemented in bomb system to work with both space and on-screen

**Comment by JacopoG** [comment]
@DeimosA something like this: the bomb system receive the bomb drop command and the ignore it if the cooldown is in progress?
