### ISSUE TITLE
Destroyed player can drop bomb without respawning

### ISSUE THREAD

**Issue by eldarht** [DeimosA/PlayingWithMagic#64]
when the player dies, the texture disappears as expected but clicking the bomb-drop-button places a bomb at center.

**Comment by DeimosA** [comment]
Could probably replace the texture with a dead player texture and remove the entitys playercomponent (which should stop its processing, mostly)

**Comment by DeimosA** [comment]
removing the PlayerComponent on death would stop it from processing, but the bomb system doesn't check this and would just return 0,0 as position and drop the bomb in the middle of the screen.

It has to check if there is a local player before dropping the bomb

**Comment by eldarht** [comment]
> Could probably replace the texture with a dead player texture and remove the entitys playercomponent (which should stop its processing, mostly)

There is an animation for it in animation sheet, but stopping on the final frame would require changing default State (what it turns to after completing an animation) and adding a row to the animation sheet with only the dead body.

**Comment by eldarht** [comment]
> removing the PlayerComponent on death would stop it from processing, but the bomb system doesn't check this and would just return 0,0 as position and drop the bomb in the middle of the screen.

Given that the components are pooled. Is there no way to destroy the entire entity? instantiating it again should be quick.
